#!/bin/sh

NODE_APP="server.js"
APP_DIR="/home/pi/ambi-tv-remote"
PID_FILE=$APP_DIR/pid/app.pid
LOG_FILE=$APP_DIR/log/app.log
NODE_PATH=$APP_DIR/app/controllers
PORT=5000
NODE_EXEC="/usr/local/bin/node"

###############

# REDHAT chkconfig header

# chkconfig: - 58 74
# description: node-app is the script for starting a node app on boot.
### BEGIN INIT INFO
# Provides: node
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start and stop node
# Description: Node process for app
### END INIT INFO

start_app (){
    if [ -f $PID_FILE ]
    then
        echo "$PID_FILE exists, process is already running or crashed"
	kill `cat $PID_FILE`
	rm $PID_FILE
    fi
    echo "Starting node app..."
    PORT=$PORT NODE_PATH=$NODE_PATH $NODE_EXEC $APP_DIR/$NODE_APP  1>$LOG_FILE 2>&1 &
    echo $! > $PID_FILE;
    wget -q -4 --post-data='' --retry-connrefused http://localhost:5000/remote/launch -O /dev/null
    echo Done
}

stop_app (){
    if [ ! -f $PID_FILE ]
    then
        echo "$PID_FILE does not exist, process is not running"
    else
        echo "Stopping $APP_DIR/$NODE_APP ..."
        echo "Killing `cat $PID_FILE`"
        kill `cat $PID_FILE`;
        rm -f $PID_FILE;
        echo "Node stopped"
    fi
}

case "$1" in
    start)
        start_app
    ;;

    stop)
        stop_app
    ;;

    restart)
        stop_app
        start_app
    ;;

    status)
        if [ -f $PID_FILE ]
        then
            PID=`cat $PID_FILE`
            if [ -z "`ps -ef | grep $PID | grep -v grep`" ]
            then
                echo "Node app stopped but pid file exists"
            else
                echo "Node app running with pid $PID"

            fi
        else
            echo "Node app stopped"
        fi
    ;;

    *)
        echo "Usage: /etc/init.d/node-app {start|stop|restart|status}"
    ;;
esac

